CREATE TABLE store (
	store_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	store_name VARCHAR(50) NOT NULL,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product (
	product_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	product_name VARCHAR(150) NOT NULL,
	product_desc VARCHAR(300) NOT NULL,
	sku VARCHAR(10) NOT NULL,
	price DECIMAL(5,2) NOT NULL,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stock (
    stock_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	store_id BIGINT UNSIGNED NOT NULL,
	product_id BIGINT UNSIGNED NOT NULL,
	product_cnt INT UNSIGNED NOT NULL,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer_order (
	order_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status INT UNSIGNED NOT NULL DEFAULT 1,	
	first_name VARCHAR(50) NOT NULL,
	last_name  VARCHAR(50) NOT NULL,
	email      VARCHAR(400) NOT NULL,
	phone      VARCHAR(20) NOT NULL,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_item (
	order_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	order_id BIGINT UNSIGNED NOT NULL,
	stock_id BIGINT UNSIGNED NOT NULL,
	item_cnt INT UNSIGNED NOT NULL,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
